### ISSUE TITLE
Bump Unity to latest available version

### ISSUE THREAD

**Issue by nagi-desuuu** [Expugn/priconne-image-extractor#1]
Recently, an upgrade to unity, the engine the game uses, has been implemented, leaving programs like AssetStudio unable to read assets since version info from the individual .unity3d files have been stripped.

Manually obtaining the version info by looking at the game executable directly on Notepad still won't extract the required assets. (unless something comes up that I haven't tried...)

**Comment by Expugn** [comment]
I've been doing some research on a fix over the past few days, but most publicly available sources for `.unity3d` extracting/exporting don't support priconne's latest unity files. I'd prefer to wait for a stable library to support these changes before updating this tool, as my quick changes/patches may be unstable.

If you're desperate to grab images, esterTion's unity-texture-toolkit works great for exporting this new asset format: <https://github.com/esterTion/unity-texture-toolkit>

A quick rundown on how to set it up:
- Only `UnityAsset.php` and `UnityBundle.php` are needed
- Ubuntu/Linux is preferred (I've tried Windows/Mac OSX/Raspian, but all seem to have issues compiling one of the dependencies <https://github.com/kjdev/php-ext-lz4/>)
- Some changes in `UnityAsset.php` may need to be made, depending on your installation of <https://github.com/ARM-software/astc-encoder>
  - See the following line in `UnityAsset.php#exportTo()`:
  ```
  exec('astcenc -d output.astc output.tga -silentmode');
  ```
  `-d` may be an unrecognized mode (change it to `ds`) and `-silentmode` may not be a supported argument
- While the example code in `README.md` is good enough, there may be some issues regarding memory leaks. This is where you'll have to figure out how to avoid said leaks from screwing up your memory usage.
- `unity-texture-toolkit` does NOT support the DMM version of `priconne-jp`'s Texture2D files (aka, Windows). If you're using `Expugn/priconne-image-extractor` to grab manifest data, find any mention of `Windows` and replace it with `iOS` in `app.js`.
  - As an example:
  ```
  /Jpn/AssetBundles/Windows/manifest/manifest_assetmanifest
  ```
  change this to...
  ```
  /Jpn/AssetBundles/iOS/manifest/manifest_assetmanifest
  ```
  - Also you can comment out the `deserialize()` call in `app.js#run()` because it won't work anyways:
  ```
  deserialize();
  ```
  change this to
  ```
  // deserialize();
  ```

Anyways, sorry for the inconvenience from me being unable to fix this repository/tool for now. Will update this issue when a fix is found/applied.

**Comment by Expugn** [comment]
Fixed `priconne-image-extractor` as of <https://github.com/Expugn/priconne-image-extractor/commit/2c4899f6003ec9ddbfb9a106133aeedd52765ed3>.

Read <https://github.com/Expugn/priconne-image-extractor#regarding-priconne-jps-unity-update-future-manual-updates-may-be-needed> for process on how to update Unity version in case this happens again.
